@startuml カレー
Title カレーを作る
start
:材料を用意する;
:お米を研ぐ;
fork
:お米を炊く;
:ライス]
fork again
:肉を切る;
:野菜を切る;
:鍋に火をかける;
:肉を入れる;
:野菜を入れる;
:水を入れる;
:カレールウを入れる;
:まて;
:カレー]
end fork
:お米をお皿にIN!;
:カレールウIN!;
:カレーライス]
stop

@enduml