@startuml 図7-10

|客|
|客|
|店員|
|店員|

|客|
start
:弁当をレジに持っていく;
|客|

|店員|
fork
|店員|

|客|
:お金を支払う;
|客|

|店員|
:清算する;
fork again
if (温めますか？) then (Yes)
:弁当を温める;
else (No)
endif
:弁当を袋に入れる;
end fork
|店員|

|客|
:弁当を手に持つ;
stop
|客|

@enduml