@startuml ホテル予約と利用者
class 利用者{
-名前
-住所
-電話番号
}
class ホテル{
-部屋
}
class 部屋{
-タイプ
-価格
-キャンペーン価格
}
class 予約{
-チェックイン日
-滞在期間
-値段
}
ホテル "1" o-- "*" 利用者:会員として登録
予約 <-- 利用者
left to right direction
ホテル "1"*--"*" 部屋
@enduml