@startuml オブジェクト図
left to right direction
object "<u>ホテル部屋番号:ホテル</u>" as k2 {
301号室
302号室
303号室
}

object "<u>宿泊客1:宿泊客</u>" as A {
名前=Aさん
}
object "<u>宿泊客2:宿泊客</u>" as B {
名前=Bさん
}
object "<u>301号室: 部屋</u>" as 301 {
部屋タイプ=シングル
価格=9,000円
キャンペーン価格 = 11,000円
}
object "<u>302号室: 部屋</u>" as 302 {
部屋タイプ=シングル
価格=9,000円
キャンペーン価格 = 11,000円
}
object "<u>303号室: 部屋</u>" as 303 {
部屋タイプ=シングル
価格=9,000円
キャンペーン価格 = 11,000円
}
k2 -- 301
k2 -- 302
k2 -- 303
A -- 301
B -- 302
@enduml