@startuml 演習3-7_OBJ_注文のオブジェクト図
class 重要顧客{
    名前 高橋洋平
    住所
}

class 顧客1{
    名前 高田理恵
    住所
}

class 顧客2{
    名前 大坪直之
    住所
}

class 注文_V12345{
    注文日 11月21日
    数量 2
}

class 注文1_R8765{
    注文日 11月21日
    数量 1
}

class 注文2_R8765{
    注文日12月23日
}
重要顧客 "1"--"*"注文_V12345
重要顧客 "1"--"*"注文1_R8765
顧客1 "1"--"*"注文2_R8765

@enduml