@startuml ハンバーガーショップ
class 注文{
    合計
}
class 注文明細{
    数量
    小計
}
class 割引クーポン{
    値引き額
    期限
}
class カップ{
    サイズ
}
class ドリンク{
    種別
}
class 商品{
    名称
    単価
}
class フード
class レシピ
class ハンバーガー{
    種別
}
class ポテト{
    サイズ
}
class 材料
left to right direction
注文 o-- 注文明細 :1.*
注文明細 -- 割引クーポン :0..* 
割引クーポン -- 注文明細 :0..1
注文明細  "1"--"0..*"  商品
カップ --ドリンク :1..3
カップ --ドリンク :0..*
ドリンク --|> 商品
フード --|> 商品
フード "1"--"1" レシピ
ハンバーガー --|> フード
ポテト --|> フード
材料 --o ハンバーガー :1..*
材料 --o ハンバーガー :1..*
材料 <|-- パン
材料 <|-- 肉
材料 <|-- 野菜
材料 <|-- チーズ
@enduml