@startuml ハンバーガーショップ
title 業務内容
|顧客|
|スタッフ|
|厨房|

|スタッフ|
start
:挨拶をする;
:注文を聞く;

|顧客|
:注文をする;

|スタッフ|
:注文を確認する;

    fork
    :代金を請求する;
    |顧客|
    :代金を払う;
    |スタッフ|
    :清算する;
    fork again
    :料理を依頼する;
    |厨房|
    :商品を料理する;
    |スタッフ|
    end fork
:テイクアウトかどうか聞く;
    if () is (テイクアウト) then
    :袋に入れる;
    else (店内)
    :トレイに乗せる;
endif
:商品を渡す;
|顧客|
:商品を受け取る;
stop
@enduml