@startuml 演習6-3_ステートマシン図_診察予約システム
state メニュー
state 予約と確認
state あなたの順番
state 今の順番

[*] -right-> メニュー: 接続する
メニュー -right-> [*]
メニュー --down-> 予約と確認: 予約と確認ボタン\nを押す
メニュー <-up-- 予約と確認: 取り消しボタン\nを押す
予約と確認 -right-> あなたの順番: 登録ボタンを押す
予約と確認 -right-> あなたの順番: 確認ボタンを押す
あなたの順番 -up-> メニュー: メニューボタン\nを押す
メニュー <-up-- 今の順番: メニューボタン\nを押す
メニュー --down-> 今の順番: 今の順番ボタン\nを押す
@enduml