@startuml クラス図
left to right direction
class ライントレーサー{}
class 光センサー{}
class 右モータ{}
class 左モータ{}
class CPU{}
class 電源スイッチ{}
ライントレーサー "1" -- "1" 光センサー
ライントレーサー "1" -- "1" 右モータ
ライントレーサー "1" -- "1" 左モータ
ライントレーサー "1" -- "1" CPU
ライントレーサー "1" -- "1" 電源スイッチ
@enduml