@startuml シーケンス図
actor 申請者
actor 承認者
actor 経理担当者
actor 交通清算システム
rectangle 出張管理システム{
    usecase 出張申請を登録する
    usecase 出張申請を提出する
    usecase 出張申請を承認する
    usecase 出張申請を却下する
    usecase 出張申請を差し戻す
    usecase 出張申請を確認する    
}
出張申請を登録する <-- 申請者
出張申請を登録する <-- 交通清算システム
出張申請を提出する <-- 申請者
出張申請を承認する <-- 承認者
出張申請を却下する <-- 承認者
出張申請を差し戻す <-- 承認者
出張申請を確認する <-- 承認者
出張申請を確認する <-- 経理担当者
@enduml